# Generated by nixos-generate-config (template — run `sudo nixos-generate-config --show-hardware-config` on the target machine to get the real one)
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "bcache"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "uinput"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2224776d-804f-4bc6-b26d-63e5f20fcb7f";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2224776d-804f-4bc6-b26d-63e5f20fcb7f";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2224776d-804f-4bc6-b26d-63e5f20fcb7f";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "noatime"
      "compress=zstd"
    ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/18E5-E8FE";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  # External HDD0 (btrfs)
  fileSystems."/HDD0_root" = {
    device = "/dev/disk/by-uuid/fe687bf7-13bb-4e2c-bd26-f944efba5291";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
    ];
  };

  fileSystems."/HDD0" = {
    device = "/dev/disk/by-uuid/fe687bf7-13bb-4e2c-bd26-f944efba5291";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
      "acl"
      "subvol=current"
    ];
  };

  # External HDD1 (btrfs)
  fileSystems."/HDD1_root" = {
    device = "/dev/disk/by-uuid/1aabd57e-7896-4e38-a75b-50dbadff26d6";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
    ];
  };

  fileSystems."/HDD1" = {
    device = "/dev/disk/by-uuid/1aabd57e-7896-4e38-a75b-50dbadff26d6";
    fsType = "btrfs";
    options = [
      "defaults"
      "nofail"
      "subvol=current"
    ];
  };

  swapDevices = [
    #{ device = "/swapfile";
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
